# câu 1: ví dụ về cộng trừ 2 ma trận

In [ ]:
import numpy as np
_a = [ [ 1, 2, 3 ], [ 4, 5, 6 ] ]
_b = [ [ 2, 3, 5], [7, 9, 21] ]
a = np.array(_a) # create matrix a
b = np.array(_b) # create matrix b
print(np.add(a, b)) # Add 
print(np.subtract(a, b)) # Sub
print(a + b) # Add 
print(a - b) # Sub


[[ 3  5  8]
 [11 14 27]]
[[ -1  -1  -2]
 [ -3  -4 -15]]
[[ 3  5  8]
 [11 14 27]]
[[ -1  -1  -2]
 [ -3  -4 -15]]


# Câu 2: dùng pandas xử lý yêu cầucầu

* Đọc CSV thành Dataframe và hiển thị
* Hãy chuyển index mặc định thành giá trị cột id

In [ ]:
import pandas as pd
df = pd.read_csv('drive/MyDrive/ML/pandaEXCEL.csv') # load file csv
df.head()
df_setid = df.set_index('ID')          
df_setid.head()

X   Y   Z
ID            
1   78  84  86
2   85  94  97
3   80  83  73
4   96  94  96
5   86  86  83

* Sắp xếp dữ liễu theo nhiều cột (sort)

In [ ]:
df.sort_values(by=['X'])

ID   X   Y   Z
0   1  78  84  86
2   3  80  83  73
1   2  85  94  97
4   5  86  86  83
3   4  96  94  96

In [ ]:
df.sort_values(by=['Y'])

ID   X   Y   Z
2   3  80  83  73
0   1  78  84  86
4   5  86  86  83
1   2  85  94  97
3   4  96  94  96

In [ ]:
df.sort_values(by=['Z'])

ID   X   Y   Z
2   3  80  83  73
4   5  86  86  83
0   1  78  84  86
3   4  96  94  96
1   2  85  94  97

* Chọn một cột cụ thể và hiển thị nó

In [ ]:
df.Z

0    86
1    97
2    73
3    96
4    83
Name: Z, dtype: int64

* Chọn 2 hàng đầu tiền và hiển thị chúng

In [ ]:
df.iloc[0:2]

ID   X   Y   Z
0   1  78  84  86
1   2  85  94  97

* Hãy chọn một hàng dựa trên một điều kiện giá trị của cột

In [ ]:
df[df.X==80]

ID   X   Y   Z
2   3  80  83  73

* Thay đổi một vài giá trị thành NaN ở CSV, sau đó đọc lên thành Dataframe và
thay thế chúng bằng giá trị 0


In [ ]:
df_Nan = df
df_Nan.loc[2, 'Z'] = np.nan # Replace some places with N/A values
df_Nan.loc[3, 'Y'] = np.nan
df_Nan.loc[4, 'Y'] = np.nan 
df_Nan.loc[2, 'X'] = np.nan
print(df_Nan)

   ID     X     Y     Z
0   1  78.0  84.0  86.0
1   2  85.0  94.0  97.0
2   3   NaN  83.0   NaN
3   4  96.0   NaN  96.0
4   5  86.0   NaN  83.0


In [ ]:
df_Nan.fillna(0) # Fill all N/A values with zero 

ID     X     Y     Z
0   1  78.0  84.0  86.0
1   2  85.0  94.0  97.0
2   3   0.0  83.0   0.0
3   4  96.0   0.0  96.0
4   5  86.0   0.0  83.0

* Ở cột Z chuyển giá trị lớn hơn 90 là True và nhỏ hơn là False trong Dataframe

In [ ]:
df.Z = (df.Z > 90)
print(df)

   ID     X     Y      Z
0   1  78.0  84.0  False
1   2  85.0  94.0   True
2   3   NaN  83.0  False
3   4  96.0   NaN   True
4   5  86.0   NaN  False


* Chuyển Dataframe trên thành 2 Dataframe d1 và d2; d1 chứa cột X và Y, d2 chứa cột Z; cuối cùng d3 là thành quả của nối 2 Dataframe d1 và d2

In [ ]:
d1 = pd.DataFrame(df, columns = ['X', 'Y'])
d2 = pd.DataFrame(df, columns = ['Z'])
d3 = pd.merge(d1, d2, left_index=True, right_index=True)
print(d3)

      X     Y      Z
0  78.0  84.0  False
1  85.0  94.0   True
2   NaN  83.0  False
3  96.0   NaN   True
4  86.0   NaN  False


* Dùng tính năng thống kê hãy hiển thị kết quả thông kể các giá trị thuộc tính
của Dataframe

In [ ]:
d3.describe()

X          Y
count   4.000000   3.000000
mean   86.250000  87.000000
std     7.410578   6.082763
min    78.000000  83.000000
25%    83.250000  83.500000
50%    85.500000  84.000000
75%    88.500000  89.000000
max    96.000000  94.000000

### **3. Sinh viên tự tìm hiểu thực hiện lại ví dụ dùng mô hình Linear Regression trong thư viện scikit-learning bằng các thư viện sau:** bold text

Tensorflow

In [ ]:
import tensorflow as tf
import numpy as np
rng = np.random

In [ ]:
# Parameters.
learning_rate = 0.01
training_steps = 1000
display_step = 50

In [ ]:
# Training Data.
X = np.array([3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,
              7.042,10.791,5.313,7.997,5.654,9.27,3.1])
Y = np.array([1.7,2.76,2.09,3.19,1.694,1.573,3.366,2.596,2.53,1.221,
              2.827,3.465,1.65,2.904,2.42,2.94,1.3])

In [ ]:
# Weight and Bias, initialized randomly.
W = tf.Variable(rng.randn(), name="weight")
b = tf.Variable(rng.randn(), name="bias")

# Linear regression (Wx + b).
def linear_regression(x):
    return W * x + b

# Mean square error.
def mean_square(y_pred, y_true):
    return tf.reduce_mean(tf.square(y_pred - y_true))

# Stochastic Gradient Descent Optimizer.
optimizer = tf.optimizers.SGD(learning_rate)

In [ ]:
# Optimization process. 
def run_optimization():
    # Wrap computation inside a GradientTape for automatic differentiation.
    with tf.GradientTape() as g:
        pred = linear_regression(X)
        loss = mean_square(pred, Y)

    # Compute gradients.
    gradients = g.gradient(loss, [W, b])
    
    # Update W and b following gradients.
    optimizer.apply_gradients(zip(gradients, [W, b]))

In [ ]:
# Run training for the given number of steps.
for step in range(1, training_steps + 1):
    # Run the optimization to update W and b values.
    run_optimization()
    
    if step % display_step == 0:
        pred = linear_regression(X)
        loss = mean_square(pred, Y)
        print("step: %i, loss: %f, W: %f, b: %f" % (step, loss, W.numpy(), b.numpy()))

step: 50, loss: 0.478532, W: 0.480062, b: -0.820647
step: 100, loss: 0.408475, W: 0.453922, b: -0.635324
step: 150, loss: 0.353534, W: 0.430773, b: -0.471209
step: 200, loss: 0.310449, W: 0.410273, b: -0.325874
step: 250, loss: 0.276660, W: 0.392119, b: -0.197171
step: 300, loss: 0.250162, W: 0.376043, b: -0.083196
step: 350, loss: 0.229382, W: 0.361806, b: 0.017736
step: 400, loss: 0.213086, W: 0.349199, b: 0.107118
step: 450, loss: 0.200306, W: 0.338034, b: 0.186272
step: 500, loss: 0.190283, W: 0.328147, b: 0.256367
step: 550, loss: 0.182424, W: 0.319391, b: 0.318441
step: 600, loss: 0.176260, W: 0.311637, b: 0.373412
step: 650, loss: 0.171426, W: 0.304771, b: 0.422091
step: 700, loss: 0.167635, W: 0.298690, b: 0.465200
step: 750, loss: 0.164662, W: 0.293305, b: 0.503376
step: 800, loss: 0.162331, W: 0.288537, b: 0.537183
step: 850, loss: 0.160503, W: 0.284314, b: 0.567122
step: 900, loss: 0.159069, W: 0.280574, b: 0.593634
step: 950, loss: 0.157944, W: 0.277263, b: 0.617113
step: 1

Keras

In [ ]:
import numpy as np 
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras import optimizers

# 1. create pseudo data y = 2*x0 + 3*x1 + 4
X = np.random.rand(100, 2)
y =  2* X[:,0] + 3 * X[:,1] + 4 + .2*np.random.randn(100) # noise added

# 2. Build model 
model = Sequential([Dense(1, input_shape = (2,), activation='linear')])

# 3. gradient descent optimizer and loss function 
sgd = optimizers.SGD(lr=0.1)
model.compile(loss='mse', optimizer=sgd)

# 4. Train the model 
model.fit(X, y, epochs=100, batch_size=2)

/usr/local/lib/python3.9/dist-packages/keras/optimizers/optimizer_v2/gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Epoch 1/100
50/50 [==============================] - 1s 4ms/step - loss: 1.9612
Epoch 2/100
50/50 [==============================] - 0s 4ms/step - loss: 0.0392
Epoch 3/100
50/50 [==============================] - 0s 3ms/step - loss: 0.0342
Epoch 4/100
50/50 [==============================] - 0s 3ms/step - loss: 0.0306
Epoch 5/100
50/50 [==============================] - 0s 5ms/step - loss: 0.0297
Epoch 6/100
50/50 [==============================] - 0s 5ms/step - loss: 0.0307
Epoch 7/100
50/50 [==============================] - 0s 3ms/step - loss: 0.0306
Epoch 8/100
50/50 [==============================] - 0s 3ms/step - loss: 0.0306
Epoch 9/100
50/50 [==============================] - 0s 3ms/step - loss: 0.0317
Epoch 10/100
50/50 [==============================] - 0s 3ms/step - loss: 0.0307
Epoch 11/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0302
Epoch 12/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0308
Epoch 13/100
50/50 [=================

In [ ]:
model.get_weights()

[array([[1.9536649],
        [3.035438 ]], dtype=float32), array([4.031311], dtype=float32)]

Pytorch

In [ ]:
from torch.autograd import Variable
import torch

x_data = Variable(torch.Tensor([[3.0], [5.0], [7.0], [9.0], [11.0]]))
y_data = Variable(torch.Tensor([[8.0], [9.1], [10.3], [11.4], [12.6]]))

class LinearRegressionModel(torch.nn.Module):
 
    def __init__(self):
        super(LinearRegressionModel, self).__init__()
        self.linear = torch.nn.Linear(1, 1)  # One in and one out
 
    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred

our_model = LinearRegressionModel()

criterion = torch.nn.MSELoss(reduction='sum')
# optimizer = torch.optim.SGD(our_model.parameters(), lr = 0.01, weight_decay=0.9)

In [ ]:
for epoch in range(100):
 
    # Forward pass: Compute predicted y by passing
    # x to the model
    pred_y = our_model(x_data)
 
    # Compute and print loss
    loss = criterion(pred_y, y_data)
 
    # Zero gradients, perform a backward pass,
    # and update the weights.
    # optimizer.zero_grad()
    loss.backward()
    # optimizer.step()
    print('epoch {}, loss {}'.format(epoch, loss.item()))

epoch 0, loss 425.2756042480469
epoch 1, loss 425.2756042480469
epoch 2, loss 425.2756042480469
epoch 3, loss 425.2756042480469
epoch 4, loss 425.2756042480469
epoch 5, loss 425.2756042480469
epoch 6, loss 425.2756042480469
epoch 7, loss 425.2756042480469
epoch 8, loss 425.2756042480469
epoch 9, loss 425.2756042480469
epoch 10, loss 425.2756042480469
epoch 11, loss 425.2756042480469
epoch 12, loss 425.2756042480469
epoch 13, loss 425.2756042480469
epoch 14, loss 425.2756042480469
epoch 15, loss 425.2756042480469
epoch 16, loss 425.2756042480469
epoch 17, loss 425.2756042480469
epoch 18, loss 425.2756042480469
epoch 19, loss 425.2756042480469
epoch 20, loss 425.2756042480469
epoch 21, loss 425.2756042480469
epoch 22, loss 425.2756042480469
epoch 23, loss 425.2756042480469
epoch 24, loss 425.2756042480469
epoch 25, loss 425.2756042480469
epoch 26, loss 425.2756042480469
epoch 27, loss 425.2756042480469
epoch 28, loss 425.2756042480469
epoch 29, loss 425.2756042480469
epoch 30, loss 425.2

# Câu 4: Sinh viên hoàn thành code phát hiện spam với SVMs và Linear regression

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


* 
Running Example

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Machine Learning/sms_spam_perceptron.csv')
y = df.iloc[:, 0].values
y = np.where(y == 'spam', -1, 1)
X = df.iloc[:, [1, 2]].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
from sklearn.linear_model import Perceptron
p = Perceptron(max_iter=40, eta0=0.1, random_state=0)
p.fit(X_train, y_train)

Perceptron(eta0=0.1, max_iter=40)

In [ ]:
y_pred = p.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
print('Misclassified samples: %d' % (y_test != y_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Misclassified samples: 7
Accuracy: 0.77


* SVM

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

df = pd.read_csv('/content/drive/MyDrive/Machine Learning/sms_spam_svm.csv')
y = df.iloc[:, 0].values
y = np.where(y == 'spam', -1, 1)
X = df.iloc[:, [1, 2]].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

svm = SVC(kernel='linear', C=1.0, random_state=0)
svm.fit(X_train, y_train)
X_pred = svm.predict(X_test)

print('Misclassified samples: %d' % (y_test != X_pred).sum())
print('Accuracy: %.2f' % accuracy_score(y_test, X_pred))

Misclassified samples: 7
Accuracy: 0.84


* Linear regression

In [10]:
import pandas as pd
import numpy as np
# from pylab import *
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score

df = pd.read_csv('sms_spam_svm.csv')
y = df.iloc[:, 0].values
y = np.where(y == 'spam', -1, 1)
X = df.iloc[:, [1, 2]].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

model = LinearRegression()
model.fit(X_train, y_train)
X_pred = model.predict(X_test)

print('Misclassified samples: %d' % (y_test != X_pred).sum())

Misclassified samples: 45


# Câu 6:Sinh viên hoàn thiện code Decision trees trên và đánh giá kết quả nhận được so với phương pháp Logistic regression.

* Logistic regression

In [ ]:
import pandas as pd
import numpy as np
from sklearn import *
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

phishing_dataset = np.genfromtxt('/content/drive/MyDrive/ML/phishing_dataset.csv', delimiter=',', dtype=np.int32)
samples = phishing_dataset[:,:-1]
targets = phishing_dataset[:, -1]

training_samples, testing_samples, training_targets, testing_targets = train_test_split( samples, targets, test_size=0.2, random_state=0)

log_classifier = LogisticRegression()
log_classifier.fit(training_samples, training_targets)

predictions = log_classifier.predict(testing_samples)
accuracy = 100.0 * accuracy_score(testing_targets, predictions)
print ("Logistic Regression accuracy: " + str(accuracy))

Logistic Regression accuracy: 91.67797376752601


* Decision Tree

In [ ]:
from sklearn import tree 

phishing_dataset = np.genfromtxt('/content/drive/MyDrive/ML/phishing_dataset.csv', delimiter=',', dtype=np.int32)
samples = phishing_dataset[:,:-1]
targets = phishing_dataset[:, -1]

training_samples, testing_samples, training_target, testing_target = train_test_split( samples, targets, test_size=0.2, random_state=0)

tree_classifier = tree.DecisionTreeClassifier()
tree_classifier.fit(training_samples, training_target)

predictions = tree_classifier.predict(testing_samples)
accuracy = 100.0 * accuracy_score(testing_target, predictions)
print("Decision Tree accuracy: %s" % str(accuracy))

Decision Tree accuracy: 96.29127091813659


### **7. Sinh viên thực hiện code phát hiện phising website bằng mô hình học máy Logistic regression và Decision trees với train và test trên tập dữ liệu** 

Logistic Regression



In [ ]:
import numpy as np
import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/Machine Learning/Phishing_Legitimate_full.csv")

#Convert data
float_cols = data.select_dtypes('float64').columns
for c in float_cols:
    data[c] = data[c].astype('float32')
    
int_cols = data.select_dtypes('int64').columns
for c in int_cols:
    data[c] = data[c].astype('int32')

data.rename(columns={'CLASS_LABEL': 'labels'}, inplace=True)

# Phân loại thông tin để tìm mối tương qua giữa tuyến tính và phi tuyến tính của các labels và feature
from sklearn.feature_selection import mutual_info_classif
X = data.drop(['id', 'labels'], axis=1)
y = data['labels']
discrete_features = X.dtypes == int
mi_scores = mutual_info_classif(X, y, discrete_features=discrete_features)
mi_scores = pd.Series(mi_scores, name='MI Scores', index=X.columns)
mi_scores = mi_scores.sort_values(ascending=False)

# Dùng LogisticRegression
# Chia data thành các tập và kiểm tra
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=50)

# Tiêu chuẩn hóa data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Xác dịnh mô hình của Logistic Regression
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def loss(y_true, y_pred):
    return (-y_true * np.log(y_pred) - (1 - y_true) * np.log(1 - y_pred)).mean()

def gradient(X, y, weights):
    z = np.dot(X, weights)
    y_pred = sigmoid(z)
    gradient = np.dot(X.T, (y_pred - y)) / y.size
    return gradient

def train(X_train, y_train, X_test, y_test, learning_rate, epochs):
    # Khởi tạo weights
    weights = np.zeros(X_train.shape[1])
    
    # Mô hình huấn luyện sẽ như sau
    for i in range(epochs):
        # Tính grad 
        grad = gradient(X_train, y_train, weights)
        
        # Cập nhật weights
        weights -= learning_rate * grad
        
        # Đánh giá mô hình trên tập huấn luyện và kiểm tra
        train_loss = loss(y_train, sigmoid(np.dot(X_train, weights)))
        test_loss = loss(y_test, sigmoid(np.dot(X_test, weights)))
        print(f"Epoch {i + 1}/{epochs}, train loss: {train_loss:.4f}, test loss: {test_loss:.4f}")
    
    return weights

# Train mô hình logistic regression 
learning_rate = 0.5
epochs = 50
weights = train(X_train, y_train, X_test, y_test, learning_rate, epochs)

# Dự đoán trên tập kiểm tra
y_pred = sigmoid(np.dot(X_test, weights))
y_pred_binary = np.where(y_pred >= 0.5, 1, 0)

# Đánh giá sự chính xác của mô hình
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred_binary)
print("accuracy:", accuracy)

Epoch 1/50, train loss: 0.5195, test loss: 0.5213
Epoch 2/50, train loss: 0.4395, test loss: 0.4413
Epoch 3/50, train loss: 0.3927, test loss: 0.3941
Epoch 4/50, train loss: 0.3613, test loss: 0.3625
Epoch 5/50, train loss: 0.3386, test loss: 0.3395
Epoch 6/50, train loss: 0.3213, test loss: 0.3219
Epoch 7/50, train loss: 0.3075, test loss: 0.3079
Epoch 8/50, train loss: 0.2963, test loss: 0.2965
Epoch 9/50, train loss: 0.2869, test loss: 0.2869
Epoch 10/50, train loss: 0.2789, test loss: 0.2788
Epoch 11/50, train loss: 0.2720, test loss: 0.2718
Epoch 12/50, train loss: 0.2659, test loss: 0.2656
Epoch 13/50, train loss: 0.2606, test loss: 0.2602
Epoch 14/50, train loss: 0.2559, test loss: 0.2554
Epoch 15/50, train loss: 0.2516, test loss: 0.2511
Epoch 16/50, train loss: 0.2478, test loss: 0.2472
Epoch 17/50, train loss: 0.2443, test loss: 0.2437
Epoch 18/50, train loss: 0.2411, test loss: 0.2404
Epoch 19/50, train loss: 0.2382, test loss: 0.2375
Epoch 20/50, train loss: 0.2355, test lo

Decision Tree

In [ ]:
import numpy as np
import pandas as pd

data = pd.read_csv("/content/drive/MyDrive/Machine Learning/Phishing_Legitimate_full.csv")

# Convert data
float_cols = data.select_dtypes('float64').columns
for c in float_cols:
    data[c] = data[c].astype('float32')

int_cols = data.select_dtypes('int64').columns
for c in int_cols:
    data[c] = data[c].astype('int32')

data.rename(columns={'CLASS_LABEL': 'labels'}, inplace=True)

#  Phân loại thông tin để tìm mối tương qua giữa tuyến tính và phi tuyến tính của các labels và feature
from sklearn.feature_selection import mutual_info_classif

X = data.drop(['id', 'labels'], axis=1)
y = data['labels']
discrete_features = X.dtypes == int
mi_scores = mutual_info_classif(X, y, discrete_features=discrete_features)
mi_scores = pd.Series(mi_scores, name='MI Scores', index=X.columns)
mi_scores = mi_scores.sort_values(ascending=False)

class Node:
    def __init__(self, feature_idx=None, threshold=None, left=None, right=None, value=None):
        self.feature_idx = feature_idx # index của feature
        self.threshold = threshold     # Ngưỡng của việc phân chua
        self.left = left               # cây con bên phải
        self.right = right             # cây con bên trái
        self.value = value             # giá trị của node lá

class DecisionTree:
    def __init__(self, max_depth=10):
        self.max_depth = max_depth
        self.root = None

    def fit(self, X, y):
        self.root = self.build_tree(X, y, self.max_depth) # xây dựng decision tree

    def predict(self, X):
      # duyệt qua cây
        return np.array([self.traverse(x, self.root) for x in X])

    def traverse(self, x, node):
      # kiểm tra nếu node hiện tại là node lá
        if node.value is not None:
      # nếu đúng thì return về class dự đoán của label
            return node.value
      # hệ số của feature
        elif x[node.feature_idx] < node.threshold:
      # đi theo nhánh bên trái của cây
            return self.traverse(x, node.left)
        else:
      # đi theo nhánh bên phải của cây
            return self.traverse(x, node.right)

    def build_tree(self, X, y, max_depth, min_samples_leaf=1):
      # dừng nếu đạt đến độ sâu tối đa hoặc tất cả các labels đều giống nhau
        if max_depth == 0 or len(np.unique(y)) == 1 or len(X) < min_samples_leaf:
            leaf_value = np.bincount(y).argmax()
            return Node(value=leaf_value)
      # tìm feature và ngưỡng tốt nhất để split
        feature_idx, threshold = self.find_best_split(X, y)
      # dừng lại nếu không có sự phân chia nào cải thiện được thông tin
        if feature_idx is None or threshold is None:
            leaf_value = np.bincount(y).argmax()
            return Node(value=leaf_value)
      # chia data dựa trên feature và ngưỡng tìm được
        left_indices = X[:, feature_idx] < threshold
        right_indices = X[:, feature_idx] >= threshold
        left_X, left_y = X[left_indices], y[left_indices]
        right_X, right_y = X[right_indices], y[right_indices]
      # Xây dựng tính đệ quy cho cây con trái và phải
        left_subtree = self.build_tree(left_X, left_y, max_depth-1, min_samples_leaf)
        right_subtree = self.build_tree(right_X, right_y, max_depth-1, min_samples_leaf)
      # trả về nút gốc của cây con
        return Node(feature_idx=feature_idx, threshold=threshold, left=left_subtree, right=right_subtree)

    def find_best_split(self, X, y):
      # tìm số lượng feature trong ma trận của feature
        n_features = X.shape[1]
        best_feature_idx, best_threshold, best_info_gain = None, None, -1
        parent_entropy = self.entropy(y)
      # Lặp lại từng feature và từng ngưỡng để tìm ra sự phân chia tốt nhất
        for feature_idx in range(n_features):
            feature_values = X[:, feature_idx]
            thresholds = np.unique(feature_values)
            for threshold in thresholds:
                left_indices = feature_values < threshold
                right_indices = feature_values >= threshold
                left_y, right_y = y[left_indices], y[right_indices]

                child_entropy = (len(left_y) * self.entropy(left_y) + len(right_y) * self.entropy(right_y)) / len(y)
                info_gain = parent_entropy - child_entropy
      # Cập nhật feature, ngưỡng và sự tăng lên của thông tin nếu sự phân chia hiện tại tốt hơn
                if info_gain > best_info_gain:
                    best_feature_idx, best_threshold, best_info_gain = feature_idx, threshold, info_gain

        return best_feature_idx, best_threshold
    # Tính entropy của 1 bộ nhãn
    def entropy(self, y):
        _, counts = np.unique(y, return_counts=True)
        probabilities = counts / len(y)
        return -np.sum(probabilities * np.log2(probabilities))

# Train test split
X_train, X_test, y_train, y_test = train_test_split(X.values, y.values, test_size=0.5, random_state=50)

# Train decision tree
dt = DecisionTree(max_depth=10)
dt.fit(X_train, y_train)

# Tạo prediction
y_pred = dt.predict(X_test)

# Tính accuracy
accuracy = np.sum(y_pred == y_test) / len(y_test)
print("accuracy:", accuracy)

accuracy: 0.9644


# Câu 8: Sinh viên thực hiện code phát hiện phising website bằng mô hình học máy Logistic regression hoặc Decision trees với train và test trên tập dữ liệu phishtank\

In [ ]:
pip install tldextract

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.9/93.9 KB 5.0 MB/s eta 0:00:00


In [ ]:
pip install python-whois

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.6/109.6 KB 5.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for python-whois: filename=python_whois-0.8.0-py3-none-any.whl size=103262 sha256=506f71d6295bd6fb33bf91a3f19b25f8a973d844645a8bead4da1eb0f86bb144
  Stored in directory: /root/.cache/pip/wheels/e6/e9/d3/1e41a6c95b398de12c5a332ff28805aa44e68aa317ea60266d
Successfully built python-whois


In [ ]:
pip install cross-validition

In [ ]:
import os
import sys
import re
import matplotlib
import pandas as pd
import numpy as np
from os.path import splitext
import ipaddress as ip
import tldextract
import whois
import datetime
from urllib.parse import urlparse
df = pd.read_csv("/content/drive/MyDrive/Machine Learning/verified_online.csv")
#df=df.sample(frac=1)
df = df.sample(frac=1).reset_index(drop=True)
df.head()
len(df)
#2016's top most suspicious TLD and words
Suspicious_TLD=['zip','cricket','link','work','party','gq','kim','country','science','tk']
Suspicious_Domain=['luckytime.co.kr','mattfoll.eu.interia.pl','trafficholder.com','dl.baixaki.com.br','bembed.redtube.comr','tags.expo9.exponential.com','deepspacer.com','funad.co.kr','trafficconverter.biz']
#trend micro's top malicious domains 
def countdots(url):  
    return url.count('.')
def countdelim(url):
    count = 0
    delim=[';','_','?','=','&']
    for each in url:
        if each in delim:
            count = count + 1
    return count
import ipaddress as ip #works only in python 3

def isip(uri):
    try:
        if ip.ip_address(uri):
            return 1
    except:
        return 0
def isPresentHyphen(url):
    return url.count('-')
def isPresentAt(url):
    return url.count('@')
def isPresentDSlash(url):
    return url.count('//')
def countSubDir(url):
    return url.count('/')
def get_ext(url):
    """Return the filename extension from url, or ''."""
    
    root, ext = splitext(url)
    return ext
def countSubDomain(subdomain):
    if not subdomain:
        return 0
    else:
        return len(subdomain.split('.'))
def countQueries(query):
    if not query:
        return 0
    else:
        return len(query.split('&'))
featureSet = pd.DataFrame(columns=('url','no of dots','presence of hyphen','len of url','presence of at',\
'presence of double slash','no of subdir','no of subdomain','len of domain','no of queries','is IP','presence of Suspicious_TLD',\
'presence of suspicious domain','create_age(months)','expiry_age(months)','update_age(days)','country','file extension','label'))

featureSet = pd.DataFrame(columns=('url','no of dots','presence of hyphen','len of url','presence of at',\
'presence of double slash','no of subdir','no of subdomain','len of domain','no of queries','is IP','presence of Suspicious_TLD',\
'presence of suspicious domain','label'))

from urllib.parse import urlparse
import tldextract
def getFeatures(url, label): 
    result = []
    url = str(url)
    
    #add the url to feature set
    result.append(url)
    
    #parse the URL and extract the domain information
    path = urlparse(url)
    ext = tldextract.extract(url)
    
    #counting number of dots in subdomain    
    result.append(countdots(ext.subdomain))
    
    #checking hyphen in domain   
    result.append(isPresentHyphen(path.netloc))
    
    #length of URL    
    result.append(len(url))
    
    #checking @ in the url    
    result.append(isPresentAt(path.netloc))
    
    #checking presence of double slash    
    result.append(isPresentDSlash(path.path))
    
    #Count number of subdir    
    result.append(countSubDir(path.path))
    
    #number of sub domain    
    result.append(countSubDomain(ext.subdomain))
    
    #length of domain name    
    result.append(len(path.netloc))
    
    #count number of queries    
    result.append(len(path.query))
    
    #Adding domain information
    
    #if IP address is being used as a URL     
    result.append(isip(ext.domain))
    
    #presence of Suspicious_TLD
    result.append(1 if ext.suffix in Suspicious_TLD else 0)
    
    #presence of suspicious domain
    result.append(1 if '.'.join(ext[1:]) in Suspicious_Domain else 0 )
  
    #result.append(get_ext(path.path))
    result.append(str(label))
    return result
                  
    #Yay! finally done!  
for i in range(len(df)):
   features = getFeatures(df["url"].loc[i], df["target"].loc[i])    
   featureSet.loc[i] = features 
   featureSet.head()
   featureSet.groupby(featureSet['label']).size()
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
import sklearn.ensemble as ek
from sklearn.model_selection import train_test_split
from sklearn import tree, linear_model
from sklearn.feature_selection import SelectFromModel
import sklearn.externals
import joblib
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.pipeline import make_pipeline
from sklearn import preprocessing
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
X = featureSet.drop(['url','label'],axis=1).values
y = featureSet['label'].values
model = { "DecisionTree":tree.DecisionTreeClassifier(max_depth=10),
         "RandomForest":ek.RandomForestClassifier(n_estimators=50),
         "Adaboost":ek.AdaBoostClassifier(n_estimators=50),
         "GradientBoosting":ek.GradientBoostingClassifier(n_estimators=50),
         "GNB":GaussianNB(),
         "LogisticRegression":LogisticRegression()   
}
X_train, X_test, y_train, y_test =train_test_split(X, y ,test_size=0.2)
results = {}
for algo in model:
    clf = model[algo]
    clf.fit(X_train,y_train)
    score = clf.score(X_test,y_test)
    print ("%s : %s " %(algo, score))
    results[algo] = score   

DecisionTree : 0.9129965669445806 
RandomForest : 0.91417361451692 
Adaboost : 0.8976949485041688 
